name: clean_arch_riverpod
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  #A reactive caching and data-binding framework. Riverpod makes working with asynchronous code a breeze.
  flutter_riverpod: ^2.3.6

#A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.15

# The following adds the Cupertino Icons font to your application.
# Use with the CupertinoIcons class for iOS style icons.  
  cupertino_icons: ^1.0.8
# for adapting screen andfont size
  flutter_screenutil: ^5.9.3
# code generator (mainly used with cubit & retrofit )
  freezed: ^2.4.4
  # Annotations for the freezed code-generator. This package does nothing without freezed too.
  freezed_annotation: 2.4.4
# Automatically generate code for converting to and from JSON by annotating Dart classes
  json_serializable: ^6.9.0
  # Annotations for the json_serializable code-generator.
  json_annotation: ^4.9.0

# Networking
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  retrofit_generator: ^9.1.9
  pretty_dio_logger: ^1.4.0

#Local data source 
# SaredPreferences: Flutter plugin for reading and writing simple key-value pairs. Wraps NSUserDefaults on iOS and SharedPreferences on Android.
  shared_preferences: ^2.5.2
#shared_preferences_web: ^2.4.3
  
# Cached Network image 
  cached_network_image: ^3.3.1
# Secure Storage
  flutter_secure_storage: ^9.2.4
  
# An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics
  flutter_svg: ^2.0.17

# scroll text library 
  marquee: ^2.3.0
#Functional Programming in Dart. Purify your Dart code using efficient immutable data structures, monads, lenses and other FP tools.
  dartz: ^0.10.1

#Flutter plugin for selecting images from the Android and iOS image library, and taking new pictures with the camera.
  image_picker: ^1.0.0
  
#A package provides an easy way to add shimmer effect in Flutter project
  shimmer: ^3.0.0
 
#Hive :
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true
